// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8szPLbVabOVsMVYx9kQionnrHxSBQcDI',
    appId: '1:330383751094:web:e770917735d7ca019a3317',
    messagingSenderId: '330383751094',
    projectId: 'nsnap-bb733',
    authDomain: 'nsnap-bb733.firebaseapp.com',
    storageBucket: 'nsnap-bb733.firebasestorage.app',
    measurementId: 'G-DZNXM5E5NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD_9iOjRHoShHyg3zKK79QPSlQxrrHh18',
    appId: '1:330383751094:android:5b010b6a0fb932c09a3317',
    messagingSenderId: '330383751094',
    projectId: 'nsnap-bb733',
    storageBucket: 'nsnap-bb733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsDbOEbe6rWvX6L-SrDfRzCnNZoNjfKe4',
    appId: '1:330383751094:ios:4a98afe084aba3f19a3317',
    messagingSenderId: '330383751094',
    projectId: 'nsnap-bb733',
    storageBucket: 'nsnap-bb733.firebasestorage.app',
    androidClientId: '330383751094-luqshjoteq4hr90gv68vr9hripqec9rb.apps.googleusercontent.com',
    iosClientId: '330383751094-jr0i1103jb4di637cap1chcfkhg41kpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsDbOEbe6rWvX6L-SrDfRzCnNZoNjfKe4',
    appId: '1:330383751094:ios:4a98afe084aba3f19a3317',
    messagingSenderId: '330383751094',
    projectId: 'nsnap-bb733',
    storageBucket: 'nsnap-bb733.firebasestorage.app',
    androidClientId: '330383751094-luqshjoteq4hr90gv68vr9hripqec9rb.apps.googleusercontent.com',
    iosClientId: '330383751094-jr0i1103jb4di637cap1chcfkhg41kpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8szPLbVabOVsMVYx9kQionnrHxSBQcDI',
    appId: '1:330383751094:web:550c7272cfb57c629a3317',
    messagingSenderId: '330383751094',
    projectId: 'nsnap-bb733',
    authDomain: 'nsnap-bb733.firebaseapp.com',
    storageBucket: 'nsnap-bb733.firebasestorage.app',
    measurementId: 'G-TS5ESHSXGX',
  );

}